name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Run lint
        run: npm run lint
        working-directory: ${{ matrix.folder }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Build project
        run: npm run build
        working-directory: ${{ matrix.folder }}
